apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dev
  labels:
    app: three-tier
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-dev
  template:
    metadata:
      labels:
        app: backend-dev
        tier: backend
    spec:
      containers:
      - name: backend
        image: docker.io/vsarode000/backend-app:latest   # <your-username>
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

        envFrom:
        - configMapRef:
            name: app-config

        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_USER
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_PASSWORD

        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
